title: Berry's Blog
description: Welcome!

remote_theme: cotes2020/jekyll-theme-chirpy@v5.6.1 # (你也可以指定版本)

plugins:
  - jekyll-remote-theme
  
navigation:
  - title: Home
    url: /

  - title: About
    url: /about